name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Looks like it's not working very well for other people:
          # https://github.com/actions/setup-python/issues/436
          # cache: "pip"
          # cache-dependency-path: pyproject.toml

      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-latest

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install uv
          uv pip install --system --resolution highest --editable ".[dev,tests,anthropic,argilla,cohere,groq,hf-inference-endpoints,hf-transformers,litellm,llama-cpp,ollama,openai,outlines,vertexai,vllm]"

          python_version=$(python -c "import sys; print(sys.version_info[:2])")
          if [ "${python_version}" != "(3, 8)" ]; then
            uv pip install --system  --resolution highest --editable ".[mistralai,instructor]"
          fi;
          # We're using a custom fork since otherwise LLM-Blender cannot be installed
          # due to a dependency mismatch on their end, solved in the fork by pinning
          # the `spaCy` dependency
          uv pip install --system git+https://github.com/argilla-io/LLM-Blender.git

      - name: Lint
        run: make lint

      - name: Unit Tests
        run: make unit-tests

      - name: Integration Tests
        run: make integration-tests
        timeout-minutes: 5
